import Foundation

/// What an activation did, including the exact bytes written. Tests assert on
/// these strings instead of re-reading the files.
public struct ActivationResult: Equatable, Sendable {
    public var providerID: String
    public var modelSlug: String
    public var catalogURL: URL
    public var configURL: URL
    public var authURL: URL
    public var backupConfigURL: URL?
    public var backupAuthURL: URL?
    public var templateSourceDescription: String
    public var warnings: [String]
    public var catalogJSON: String
    public var configTOML: String
    public var authJSON: String
}

/// Turns an activated provider + model into the files Codex reads.
///
/// Order of operations is deliberate: every backup is taken before any write, the
/// catalog is written before the config that references it, and each file is
/// published with an atomic rename. A failure therefore leaves Codex with either
/// the old config or the new one, never a truncated file.
public struct CodexConfigWriter: @unchecked Sendable {
    public let paths: CodexPaths
    public let fileManager: FileManager
    public let templateSource: CatalogTemplateSource
    public let now: () -> Date

    /// wire_api accepts exactly one value in current Codex. It is never derived
    /// from user input, so an unsupported protocol can never be written.
    public static let wireAPIValue = "responses"

    public enum WriterError: Error, LocalizedError, Equatable {
        case invalidProviderID(String)
        case emptyBaseURL(String)
        case emptyModelSlug(String)
        case emptyCommandAuth(String)

        public var errorDescription: String? {
            switch self {
            case let .invalidProviderID(id):
                return "提供商 ID 不合法（只能用字母、数字、下划线、连字符）: " + id
            case let .emptyBaseURL(id):
                return "提供商 " + id + " 缺少 base_url"
            case let .emptyModelSlug(id):
                return "提供商 " + id + " 的模型 slug 不能为空"
            case let .emptyCommandAuth(id):
                return "提供商 " + id + " 选择了外部命令认证但没有填写命令"
            }
        }
    }

    public init(
        paths: CodexPaths,
        templateSource: CatalogTemplateSource,
        fileManager: FileManager = .default,
        now: @escaping () -> Date = Date.init
    ) {
        self.paths = paths
        self.templateSource = templateSource
        self.fileManager = fileManager
        self.now = now
    }

    // MARK: - Activation

    public func activate(
        provider: ProviderConfiguration,
        model: ModelConfiguration,
        configuration: CodexBridgerConfiguration,
        managedProviderIDs: Set<String> = []
    ) throws -> ActivationResult {
        try validate(provider: provider, model: model)

        // The catalog comes from the same writer the save path uses, so a catalog written by
        // activating and one written by saving a provider can never drift apart.
        let catalogWriter = ModelCatalogWriter(
            paths: paths,
            templateSource: templateSource,
            fileManager: fileManager
        )
        let renderedCatalog = try catalogWriter.render(
            provider: provider,
            preferredTemplateSlug: configuration.catalogTemplateSlug
        )
        let catalogJSON = renderedCatalog.json

        let catalogURL = renderedCatalog.url
        let configURL = paths.configTOML
        let authURL = paths.authJSON

        // 1. Back up before touching anything — but only what this app cannot reproduce.
        //
        // A config naming a provider we manage was generated by this app and is fully
        // reconstructable from its own stored configuration, so every switch used to drop
        // another near-identical copy into the backup folder. Backing those up only grows the
        // directory. A config we do NOT manage is somebody else's work and may be the only copy
        // that exists, so that one is always saved before it is replaced.
        let replacedProviderID = CodexConfigReader(paths: paths, fileManager: fileManager)
            .snapshot().modelProviderID
        let isOurs = replacedProviderID.map { managedProviderIDs.contains($0) } ?? false
        var warnings: [String] = []

        let backups = BackupManager(paths: paths, fileManager: fileManager)
        let stamp = now()
        var backupConfigURL: URL?
        var backupAuthURL: URL?
        if isOurs {
            warnings.append("已跳过备份：当前配置由本软件生成，可随时重新生成。")
        } else {
            // Named after the provider the file actually holds, not the one being activated, so
            // the file describes its own contents.
            let segment = replacedProviderID ?? provider.id
            backupConfigURL = try backups.backup(configURL, kind: .config, provider: segment, now: stamp)
            backupAuthURL = try backups.backup(authURL, kind: .auth, provider: segment, now: stamp)
        }

        // 2. Catalog first: config.toml will point at it.
        try catalogWriter.write(renderedCatalog)

        // 3. config.toml
        var document = TOMLDocument(text: existingConfigText())
        applyTopLevel(to: &document, provider: provider, model: model,
                      configuration: configuration, catalogURL: catalogURL)
        // Drop every other [model_providers.*] table before writing ours.
        //
        // Replacing only our own table left the previous provider behind, complete with its
        // base_url and bearer token, so Codex kept a resolvable dead provider pointing at a
        // service the app no longer manages. Only the provider tables go; every other setting the
        // user has in config.toml is left exactly as it was.
        for stale in staleProviderTablePaths(in: document, keeping: provider.id) {
            document.removeTableRegion(rootPath: stale)
        }
        document.replaceTableRegion(
            rootPath: ["model_providers", provider.id],
            rendered: renderProviderSection(provider)
        )
        let configTOML = document.text
        try AtomicFile.write(configTOML, to: configURL, fileManager: fileManager)

        // 4. auth.json
        let authObject = makeAuthObject(provider: provider, warnings: &warnings)
        let authJSON = try renderJSON(authObject)
        try AtomicFile.write(authJSON, to: authURL, fileManager: fileManager)

        return ActivationResult(
            providerID: provider.id,
            modelSlug: model.slug,
            catalogURL: catalogURL,
            configURL: configURL,
            authURL: authURL,
            backupConfigURL: backupConfigURL,
            backupAuthURL: backupAuthURL,
            templateSourceDescription: templateSource.sourceDescription,
            warnings: warnings,
            catalogJSON: catalogJSON,
            configTOML: configTOML,
            authJSON: authJSON
        )
    }

    /// `[model_providers.X]` tables other than the one being activated.
    ///
    /// Only the two-segment tables are collected: `[model_providers.X.auth]` is a child of its
    /// parent and disappears with it.
    private func staleProviderTablePaths(in document: TOMLDocument, keeping keep: String) -> [[String]] {
        document.tablePaths().filter { path in
            path.count == 2 && path[0] == "model_providers" && path[1] != keep
        }
    }

    // MARK: - Validation

    private func validate(provider: ProviderConfiguration, model: ModelConfiguration) throws {
        guard ProviderConfiguration.isValidIdentifier(provider.id) else {
            throw WriterError.invalidProviderID(provider.id)
        }
        guard !provider.baseURL.trimmingCharacters(in: .whitespaces).isEmpty else {
            throw WriterError.emptyBaseURL(provider.id)
        }
        guard !model.slug.trimmingCharacters(in: .whitespaces).isEmpty else {
            throw WriterError.emptyModelSlug(provider.id)
        }
        if provider.credentialMode == .command && provider.commandAuth.command.isEmpty {
            throw WriterError.emptyCommandAuth(provider.id)
        }
    }

    // MARK: - config.toml rendering

    private func existingConfigText() -> String {
        guard fileManager.fileExists(atPath: paths.configTOML.path) else { return "" }
        return (try? String(contentsOf: paths.configTOML, encoding: .utf8)) ?? ""
    }

    private func applyTopLevel(
        to document: inout TOMLDocument,
        provider: ProviderConfiguration,
        model: ModelConfiguration,
        configuration: CodexBridgerConfiguration,
        catalogURL: URL
    ) {
        document.setTopLevel(key: "model_provider", rawValue: TOMLValueWriter.string(provider.id))
        document.setTopLevel(key: "model", rawValue: TOMLValueWriter.string(model.slug))
        document.setTopLevel(
            key: "model_catalog_json",
            rawValue: TOMLValueWriter.string(catalogURL.path)
        )

        // The effort written here must be one the activated model advertises.
        let effort = configuration.modelReasoningEffort ?? model.defaultReasoningEffort
        document.setTopLevel(
            key: "model_reasoning_effort",
            rawValue: TOMLValueWriter.string(effort.rawValue)
        )

        if let summary = configuration.modelReasoningSummary {
            document.setTopLevel(
                key: "model_reasoning_summary",
                rawValue: TOMLValueWriter.string(summary.rawValue)
            )
        }
        if let verbosity = configuration.modelVerbosity {
            document.setTopLevel(
                key: "model_verbosity",
                rawValue: TOMLValueWriter.string(verbosity.rawValue)
            )
        }
        if let supports = configuration.modelSupportsReasoningSummaries {
            document.setTopLevel(
                key: "model_supports_reasoning_summaries",
                rawValue: TOMLValueWriter.bool(supports)
            )
        }
    }

    /// Renders [model_providers.<id>] plus its optional .auth sub-table.
    public func renderProviderSection(_ provider: ProviderConfiguration) -> [String] {
        var lines: [String] = ["[model_providers." + provider.id + "]"]
        let displayName = provider.name.trimmingCharacters(in: .whitespaces).isEmpty
            ? provider.id
            : provider.name
        lines.append("name = " + TOMLValueWriter.string(displayName))
        lines.append("base_url = " + TOMLValueWriter.string(provider.baseURL))
        lines.append("wire_api = " + TOMLValueWriter.string(CodexConfigWriter.wireAPIValue))

        switch provider.credentialMode {
        case .none:
            break
        case .bearerToken:
            if !provider.bearerToken.isEmpty {
                lines.append("experimental_bearer_token = " + TOMLValueWriter.string(provider.bearerToken))
            }
        case .environmentKey:
            if !provider.environmentKeyName.isEmpty {
                lines.append("env_key = " + TOMLValueWriter.string(provider.environmentKeyName))
            }
            if !provider.environmentKeyInstructions.isEmpty {
                lines.append("env_key_instructions = " + TOMLValueWriter.string(provider.environmentKeyInstructions))
            }
        case .command:
            break
        }

        // requires_openai_auth is independent of the credential source.
        if provider.requiresOpenAIAuth {
            lines.append("requires_openai_auth = true")
        }
        if !provider.queryParams.isEmpty {
            lines.append("query_params = " + TOMLValueWriter.inlineTable(
                provider.queryParams.sorted { $0.key < $1.key }.map { ($0.key, $0.value) }
            ))
        }
        if !provider.httpHeaders.isEmpty {
            lines.append("http_headers = " + TOMLValueWriter.inlineTable(
                provider.httpHeaders.sorted { $0.key < $1.key }.map { ($0.key, $0.value) }
            ))
        }
        if !provider.environmentHTTPHeaders.isEmpty {
            lines.append("env_http_headers = " + TOMLValueWriter.inlineTable(
                provider.environmentHTTPHeaders.sorted { $0.key < $1.key }.map { ($0.key, $0.value) }
            ))
        }
        if let value = provider.requestMaxRetries {
            lines.append("request_max_retries = " + TOMLValueWriter.int(value))
        }
        if let value = provider.streamMaxRetries {
            lines.append("stream_max_retries = " + TOMLValueWriter.int(value))
        }
        if let value = provider.streamIdleTimeoutMs {
            lines.append("stream_idle_timeout_ms = " + TOMLValueWriter.int(value))
        }
        if let value = provider.supportsWebsockets {
            lines.append("supports_websockets = " + TOMLValueWriter.bool(value))
        }
        if let value = provider.supportsStandaloneWebSearch {
            lines.append("supports_standalone_web_search = " + TOMLValueWriter.bool(value))
        }

        if provider.credentialMode == .command && !provider.commandAuth.command.isEmpty {
            lines.append("")
            lines.append("[model_providers." + provider.id + ".auth]")
            lines.append("command = " + TOMLValueWriter.string(provider.commandAuth.command))
            if !provider.commandAuth.args.isEmpty {
                lines.append("args = " + TOMLValueWriter.stringArray(provider.commandAuth.args))
            }
            if let value = provider.commandAuth.timeoutMs {
                lines.append("timeout_ms = " + TOMLValueWriter.int(value))
            }
            if let value = provider.commandAuth.refreshIntervalMs {
                lines.append("refresh_interval_ms = " + TOMLValueWriter.int(value))
            }
            if let cwd = provider.commandAuth.cwd, !cwd.isEmpty {
                lines.append("cwd = " + TOMLValueWriter.string(cwd))
            }
        }
        return lines
    }

    // MARK: - auth.json

    /// Merges the provider credentials into whatever auth.json already holds, so a
    /// ChatGPT login or another provider key stored there survives activation.
    private func makeAuthObject(
        provider: ProviderConfiguration,
        warnings: inout [String]
    ) -> [String: Any] {
        var object: [String: Any] = [:]
        if let data = try? Data(contentsOf: paths.authJSON),
           let existing = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            object = existing
        }

        let token = provider.bearerToken.trimmingCharacters(in: .whitespacesAndNewlines)
        let providerKeyName = provider.id
            .uppercased()
            .replacingOccurrences(of: "-", with: "_") + "_KEY"

        // Remove credentials belonging to providers we are not activating.
        //
        // This mirrors the config.toml rule: the provider we are activating replaces the one
        // before it, and its key replaces theirs. Merging into the existing object left the old
        // provider's token sitting in auth.json after a switch, so a retired service's secret
        // stayed on disk in clear text. auth.json is Codex's own credential file — `auth_mode`,
        // OPENAI_API_KEY and per-provider keys are all it holds — so anything shaped like a
        // provider key and not written by this activation is a leftover and goes.
        //
        // The previous contents were backed up before this write, so nothing is unrecoverable.
        let keep = Set(["auth_mode", "OPENAI_API_KEY", providerKeyName])
        let stale = object.keys.filter { key in
            guard !keep.contains(key) else { return false }
            let upper = key.uppercased()
            return upper.hasSuffix("_KEY") || upper.hasSuffix("_API_KEY")
        }
        for key in stale { object.removeValue(forKey: key) }

        if !token.isEmpty {
            object["auth_mode"] = "apikey"
            object["OPENAI_API_KEY"] = token
            object[providerKeyName] = token
        } else {
            if provider.credentialMode == .bearerToken {
                warnings.append("提供商选择了 Bearer Token 认证，但 token 为空，未写入 auth.json 凭据。")
            }
            if provider.requiresOpenAIAuth && object["OPENAI_API_KEY"] == nil {
                warnings.append("启用了 requires_openai_auth，但 auth.json 中没有可用的 OPENAI_API_KEY。")
            }
        }
        return object
    }

    private func renderJSON(_ object: [String: Any]) throws -> String {
        let data = try JSONSerialization.data(
            withJSONObject: object,
            options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        )
        guard var text = String(data: data, encoding: .utf8) else {
            throw ModelCatalogGenerator.GenerationError.noUsableTemplate
        }
        if !text.hasSuffix(TOMLDocument.newline) { text += TOMLDocument.newline }
        return text
    }
}
